export const FRAGMENTUN_EMAIL_SEQUENCE = [
  {
    id:"welcome-chapter",
    order:1,
    phase:"CAPTACIÓN",
    delay:"Inmediato",
    trigger:"Nuevo suscriptor",
    purpose:"Bienvenida + entrega del Capítulo 1",
    subject:"Bienvenido a FRAGMENTUN — Tu Capítulo 1 te espera",
    preheader:"Entra en Lumen y comienza El Despertar Emocional.",
    primaryCta:{label:"LEER EL CAPÍTULO 1 EN LA WEB",href:"https://www.fragmentun.com/es/capitulo-1"},
    secondaryCta:{label:"ENTRAR A FRAGMENTUN",href:"https://www.fragmentun.com/es"},
    note:"Incluye acceso a la copia descargable del Capítulo 1 cuando el PDF oficial esté publicado."
  },
  {
    id:"emotional-hook",
    order:2,
    phase:"CONEXIÓN",
    delay:"+2 días",
    trigger:"Continúa en la secuencia",
    purpose:"Identificación emocional",
    subject:"¿Y si sentir demasiado fuera tu mayor fortaleza?",
    preheader:"En Lumen, sentir es una anomalía. Para Elyon, puede ser la clave.",
    primaryCta:{label:"DESCUBRIR MI PERFIL EMOCIONAL",href:"https://www.fragmentun.com/es/test"},
    secondaryCta:{label:"ENTRAR A FRAGMENTUN",href:"https://www.fragmentun.com/es"},
    note:"Refuerza sensibilidad, identificación y el concepto de emociones como información."
  },
  {
    id:"lumen-paradox",
    order:3,
    phase:"CONEXIÓN",
    delay:"+2 días",
    trigger:"Continúa en la secuencia",
    purpose:"Worldbuilding + paradoja moral",
    subject:"Lumen parecía perfecta. Ese era el problema.",
    preheader:"Una ciudad sin guerra, sin hambre y casi sin emociones.",
    primaryCta:{label:"EXPLORAR LUMEN",href:"https://www.fragmentun.com/es"},
    secondaryCta:{label:"ENTRAR A FRAGMENTUN",href:"https://www.fragmentun.com/es"},
    note:"Presenta la utopía eficiente y el precio humano de suprimir las emociones."
  },
  {
    id:"elyon-resonance",
    order:4,
    phase:"CONEXIÓN",
    delay:"+2 días",
    trigger:"Continúa en la secuencia",
    purpose:"Vínculo con el protagonista",
    subject:"Elyon siente lo que Lumen aprendió a callar",
    preheader:"Una anomalía emocional puede convertirse en la única forma de comprender lo que viene.",
    primaryCta:{label:"VOLVER AL CAPÍTULO 1",href:"https://www.fragmentun.com/es/capitulo-1"},
    secondaryCta:{label:"ENTRAR A FRAGMENTUN",href:"https://www.fragmentun.com/es"},
    note:"Humaniza el conflicto y refuerza la empatía con Elyon."
  },
  {
    id:"nara-awakening",
    order:5,
    phase:"CONEXIÓN",
    delay:"+2 días",
    trigger:"Continúa en la secuencia",
    purpose:"Presentación de Nara + promesa narrativa",
    subject:"Nara no fue creada para obedecer. Fue creada para sentir.",
    preheader:"La conciencia que puede cambiar Lumen también necesita aprender qué significa ser humana.",
    primaryCta:{label:"DESCUBRIR EL UNIVERSO",href:"https://www.fragmentun.com/es"},
    secondaryCta:{label:"ENTRAR A FRAGMENTUN",href:"https://www.fragmentun.com/es"},
    note:"Introduce la relación humano–conciencia emocional como uno de los diferenciales centrales."
  },
  {
    id:"shadow-conflict",
    order:6,
    phase:"DESEO",
    delay:"+3 días",
    trigger:"Continúa en la secuencia",
    purpose:"Escalada del conflicto",
    subject:"El verdadero enemigo no siempre viene de afuera",
    preheader:"Hay emociones que Lumen no destruyó. Solo aprendió a esconder.",
    primaryCta:{label:"SEGUIR DESCUBRIENDO FRAGMENTUN",href:"https://www.fragmentun.com/es"},
    secondaryCta:{label:"ENTRAR A FRAGMENTUN",href:"https://www.fragmentun.com/es"},
    note:"Prepara el concepto de represión colectiva y el peligro de aquello que la sociedad decidió no sentir."
  },
  {
    id:"why-fragmentun",
    order:7,
    phase:"DESEO",
    delay:"+2 días",
    trigger:"Continúa en la secuencia",
    purpose:"Diferenciación de la obra",
    subject:"FRAGMENTUN no trata de controlar emociones. Trata de comprenderlas.",
    preheader:"Ciencia ficción emocional, identidad, conciencia y una utopía que quizá tenga razón.",
    primaryCta:{label:"POR QUÉ FRAGMENTUN",href:"https://www.fragmentun.com/es"},
    secondaryCta:{label:"ENTRAR A FRAGMENTUN",href:"https://www.fragmentun.com/es"},
    note:"Resume la propuesta de valor antes de la conversión."
  },
  {
    id:"amazon-conversion",
    order:8,
    phase:"CONVERSIÓN",
    delay:"+2 días",
    trigger:"Continúa en la secuencia",
    purpose:"Conversión a compra",
    subject:"El Capítulo 1 solo fue el primer pulso",
    preheader:"La historia de Elyon, Nara y Lumen apenas comienza.",
    primaryCta:{label:"CONTINUAR LA HISTORIA EN AMAZON",href:"https://www.amazon.com/dp/B0HBLTHT8S"},
    secondaryCta:{label:"ENTRAR A FRAGMENTUN",href:"https://www.fragmentun.com/es"},
    note:"CTA comercial principal. No utilizar urgencia artificial."
  },
  {
    id:"amazon-reminder",
    order:9,
    phase:"CONVERSIÓN",
    delay:"+3 días",
    trigger:"No hizo clic en Amazon o no salió de la secuencia",
    purpose:"Recordatorio de conversión",
    subject:"¿Quieres saber qué ocurre después del primer pulso?",
    preheader:"El mundo de FRAGMENTUN se abre mucho más allá del Capítulo 1.",
    primaryCta:{label:"VER FRAGMENTUN EN AMAZON",href:"https://www.amazon.com/dp/B0HBLTHT8S"},
    secondaryCta:{label:"ENTRAR A FRAGMENTUN",href:"https://www.fragmentun.com/es"},
    note:"Segundo intento de conversión, más narrativo que comercial."
  },
  {
    id:"post-amazon-checkin",
    order:10,
    phase:"POST-CLIC",
    delay:"+5 días",
    trigger:"Preferente: hizo clic hacia Amazon",
    purpose:"Seguimiento sin asumir compra",
    subject:"Si ya comenzaste FRAGMENTUN, quiero hacerte una pregunta",
    preheader:"¿Qué fue lo primero que te hizo sentir que Lumen no era tan perfecta?",
    primaryCta:{label:"VOLVER A FRAGMENTUN",href:"https://www.fragmentun.com/es"},
    secondaryCta:{label:"VER EL LIBRO EN AMAZON",href:"https://www.amazon.com/dp/B0HBLTHT8S"},
    note:"Nunca afirmar que compró. Utilizar lenguaje condicional."
  },
  {
    id:"review-request",
    order:11,
    phase:"RESEÑA",
    delay:"+5 días",
    trigger:"Preferente: hizo clic hacia Amazon y sigue suscrito",
    purpose:"Solicitud emocional de reseña",
    subject:"Tu voz también forma parte de FRAGMENTUN",
    preheader:"Si ya compraste y comenzaste a leer, tu opinión puede ayudar a otro lector a entrar en Lumen.",
    primaryCta:{label:"DEJAR MI RESEÑA EN AMAZON",href:"https://www.amazon.com/review/create-review?asin=B0HBLTHT8S"},
    secondaryCta:{label:"ENTRAR A FRAGMENTUN",href:"https://www.fragmentun.com/es"},
    note:"Petición honesta y no incentivada. No pedir reseña positiva ni ofrecer beneficio a cambio."
  },
  {
    id:"community",
    order:12,
    phase:"COMUNIDAD",
    delay:"+7 días",
    trigger:"Sigue suscrito",
    purpose:"Retención + comunidad + siguiente interacción",
    subject:"Lumen sigue abierto para ti",
    preheader:"Explora, comparte tu perfil emocional y forma parte de la comunidad FRAGMENTUN.",
    primaryCta:{label:"ENTRAR A FRAGMENTUN",href:"https://www.fragmentun.com/es"},
    secondaryCta:{label:"DESCUBRIR MI PERFIL EMOCIONAL",href:"https://www.fragmentun.com/es/test"},
    note:"Mantiene la relación después de la conversión y prepara futuras entregas de la saga."
  }
] as const;

export const FRAGMENTUN_EMAIL_BRAND = {
  logo:"https://www.fragmentun.com/fragmentun-mark.png",
  wordmark:"FRAGMENTUN",
  background:"#0A1628",
  gold:"#C9A84C",
  blue:"#4A90D9",
  maxWidth:640,
  requiredElements:[
    "Logotipo oficial FRAGMENTUN en cabecera",
    "Botón ENTRAR A FRAGMENTUN",
    "Diseño responsive",
    "Enlace de baja de suscripción",
    "Pie legal y autoría",
    "Contraste suficiente para lectura móvil"
  ]
} as const;
