export const FRAGMENTUN_EMAIL_SEQUENCE = [
  {
    id:"welcome-chapter",
    order:1,
    phase:"CAPTACIÓN",
    delay:"Inmediato",
    trigger:"Nuevo suscriptor",
    purpose:"Bienvenida + entrega del Capítulo 1",
    subject:"Bienvenido a FRAGMENTUN — Tu Capítulo 1 te espera",
    preheader:"Entra en Lumen y comienza El Despertar Emocional.",
    primaryCta:{label:"LEER EL CAPÍTULO 1 EN LA WEB",href:"https://www.fragmentun.com/es/capitulo-1"},
    secondaryCta:{label:"ENTRAR A FRAGMENTUN",href:"https://www.fragmentun.com/es"},
    note:"Incluye acceso a la copia descargable del Capítulo 1 cuando el PDF oficial esté publicado."
  },
  {
    id:"emotional-hook",
    order:2,
    phase:"CONEXIÓN",
    delay:"+2 días",
    trigger:"Continúa en la secuencia",
    purpose:"Identificación emocional",
    subject:"¿Y si sentir demasiado fuera tu mayor fortaleza?",
    preheader:"En Lumen, sentir es una anomalía. Para Elyon, puede ser la clave.",
    primaryCta:{label:"DESCUBRIR MI PERFIL EMOCIONAL",href:"https://www.fragmentun.com/es/test"},
    secondaryCta:{label:"ENTRAR A FRAGMENTUN",href:"https://www.fragmentun.com/es"},
    note:"Refuerza sensibilidad, identificación y el concepto de emociones como información."
  },
  {
    id:"lumen-paradox",
    order:3,
    phase:"CONEXIÓN",
    delay:"+2 días",
    trigger:"Continúa en la secuencia",
    purpose:"Worldbuilding + paradoja moral",
    subject:"Lumen parecía perfecta. Ese era el problema.",
    preheader:"Una ciudad sin guerra, sin hambre y casi sin emociones.",
    primaryCta:{label:"EXPLORAR LUMEN",href:"https://www.fragmentun.com/es"},
    secondaryCta:{label:"ENTRAR A FRAGMENTUN",href:"https://www.fragmentun.com/es"},
    note:"Presenta la utopía eficiente y el precio humano de suprimir las emociones."
  },
  {
    id:"elyon-resonance",
    order:4,
    phase:"CONEXIÓN",
    delay:"+2 días",
    trigger:"Continúa en la secuencia",
    purpose:"Vínculo con el protagonista",
    subject:"Elyon siente lo que Lumen aprendió a callar",
    preheader:"Una anomalía emocional puede convertirse en la única forma de comprender lo que viene.",
    primaryCta:{label:"VOLVER AL CAPÍTULO 1",href:"https://www.fragmentun.com/es/capitulo-1"},
    secondaryCta:{label:"ENTRAR A FRAGMENTUN",href:"https://www.fragmentun.com/es"},
    note:"Humaniza el conflicto y refuerza la empatía con Elyon."
  },
  {
    id:"nara-awakening",
    order:5,
    phase:"CONEXIÓN",
    delay:"+2 días",
    trigger:"Continúa en la secuencia",
    purpose:"Presentación de Nara + promesa narrativa",
    subject:"Nara no fue creada para obedecer. Fue creada para sentir.",
    preheader:"La conciencia que puede cambiar Lumen también necesita aprender qué significa ser humana.",
    primaryCta:{label:"DESCUBRIR EL UNIVERSO",href:"https://www.fragmentun.com/es"},
    secondaryCta:{label:"ENTRAR A FRAGMENTUN",href:"https://www.fragmentun.com/es"},
    note:"Introduce la relación humano–conciencia emocional como uno de los diferenciales centrales."
  },
  {
    id:"shadow-conflict",
    order:6,
    phase:"DESEO",
    delay:"+3 días",
    trigger:"Continúa en la secuencia",
    purpose:"Escalada del conflicto",
    subject:"El verdadero enemigo no siempre viene de afuera",
    preheader:"Hay emociones que Lumen no destruyó. Solo aprendió a esconder.",
    primaryCta:{label:"SEGUIR DESCUBRIENDO FRAGMENTUN",href:"https://www.fragmentun.com/es"},
    secondaryCta:{label:"ENTRAR A FRAGMENTUN",href:"https://www.fragmentun.com/es"},
    note:"Prepara el concepto de represión colectiva y el peligro de aquello que la sociedad decidió no sentir."
  },
  {
    id:"why-fragmentun",
    order:7,
    phase:"DESEO",
    delay:"+2 días",
    trigger:"Continúa en la secuencia",
    purpose:"Diferenciación de la obra",
    subject:"FRAGMENTUN no trata de controlar emociones. Trata de comprenderlas.",
    preheader:"Ciencia ficción emocional, identidad, conciencia y una utopía que quizá tenga razón.",
    primaryCta:{label:"POR QUÉ FRAGMENTUN",href:"https://www.fragmentun.com/es"},
    secondaryCta:{label:"ENTRAR A FRAGMENTUN",href:"https://www.fragmentun.com/es"},
    note:"Resume la propuesta de valor antes de la conversión."
  },
  {
    id:"amazon-conversion",
    order:8,
    phase:"CONVERSIÓN",
    delay:"+2 días",
    trigger:"Continúa en la secuencia",
    purpose:"Conversión a compra",
    subject:"El Capítulo 1 solo fue el primer pulso",
    preheader:"La historia de Elyon, Nara y Lumen apenas comienza.",
    primaryCta:{label:"CONTINUAR LA HISTORIA EN AMAZON",href:"https://www.amazon.com/dp/B0HBLTHT8S"},
    secondaryCta:{label:"ENTRAR A FRAGMENTUN",href:"https://www.fragmentun.com/es"},
    note:"CTA comercial principal. No utilizar urgencia artificial."
  },
  {
    id:"amazon-reminder",
    order:9,
    phase:"CONVERSIÓN",
    delay:"+3 días",
    trigger:"No hizo clic en Amazon o no salió de la secuencia",
    purpose:"Recordatorio de conversión",
    subject:"¿Quieres saber qué ocurre después del primer pulso?",
    preheader:"El mundo de FRAGMENTUN se abre mucho más allá del Capítulo 1.",
    primaryCta:{label:"VER FRAGMENTUN EN AMAZON",href:"https://www.amazon.com/dp/B0HBLTHT8S"},
    secondaryCta:{label:"ENTRAR A FRAGMENTUN",href:"https://www.fragmentun.com/es"},
    note:"Segundo intento de conversión, más narrativo que comercial."
  },
  {
    id:"post-amazon-checkin",
    order:10,
    phase:"POST-CLIC",
    delay:"+5 días",
    trigger:"Preferente: hizo clic hacia Amazon",
    purpose:"Seguimiento sin asumir compra",
    subject:"Si ya comenzaste FRAGMENTUN, quiero hacerte una pregunta",
    preheader:"¿Qué fue lo primero que te hizo sentir que Lumen no era tan perfecta?",
    primaryCta:{label:"VOLVER A FRAGMENTUN",href:"https://www.fragmentun.com/es"},
    secondaryCta:{label:"VER EL LIBRO EN AMAZON",href:"https://www.amazon.com/dp/B0HBLTHT8S"},
    note:"Nunca afirmar que compró. Utilizar lenguaje condicional."
  },
  {
    id:"review-request",
    order:11,
    phase:"RESEÑA",
    delay:"+5 días",
    trigger:"Preferente: hizo clic hacia Amazon y sigue suscrito",
    purpose:"Solicitud emocional de reseña",
    subject:"Tu voz también forma parte de FRAGMENTUN",
    preheader:"Si ya compraste y comenzaste a leer, tu opinión puede ayudar a otro lector a entrar en Lumen.",
    primaryCta:{label:"DEJAR MI RESEÑA EN AMAZON",href:"https://www.amazon.com/review/create-review?asin=B0HBLTHT8S"},
    secondaryCta:{label:"ENTRAR A FRAGMENTUN",href:"https://www.fragmentun.com/es"},
    note:"Petición honesta y no incentivada. No pedir reseña positiva ni ofrecer beneficio a cambio."
  },
  {
    id:"community",
    order:12,
    phase:"COMUNIDAD",
    delay:"+7 días",
    trigger:"Sigue suscrito",
    purpose:"Retención + comunidad + siguiente interacción",
    subject:"Lumen sigue abierto para ti",
    preheader:"Explora, comparte tu perfil emocional y forma parte de la comunidad FRAGMENTUN.",
    primaryCta:{label:"ENTRAR A FRAGMENTUN",href:"https://www.fragmentun.com/es"},
    secondaryCta:{label:"DESCUBRIR MI PERFIL EMOCIONAL",href:"https://www.fragmentun.com/es/test"},
    note:"Mantiene la relación después de la conversión y prepara futuras entregas de la saga."
  }
] as const;


export const FRAGMENTUN_EMAIL_SEQUENCE_EN = [
  {
    id:"welcome-chapter-en",
    order:1,
    phase:"ACQUISITION",
    delay:"Immediate",
    trigger:"New English-language subscriber",
    purpose:"Welcome + Chapter 1 delivery",
    subject:"Welcome to FRAGMENTUN — Your Chapter 1 is waiting",
    preheader:"Enter Lumen and begin The Emotional Awakening.",
    primaryCta:{label:"READ CHAPTER 1 ON THE WEBSITE",href:"https://www.fragmentun.com/en/capitulo-1"},
    secondaryCta:{label:"ENTER FRAGMENTUN",href:"https://www.fragmentun.com/en"},
    note:"Includes access to the downloadable Chapter 1 edition once the official PDF is published."
  },
  {
    id:"emotional-hook-en",
    order:2,
    phase:"CONNECTION",
    delay:"+2 days",
    trigger:"Continues in sequence",
    purpose:"Emotional identification",
    subject:"What if feeling too much were your greatest strength?",
    preheader:"In Lumen, feeling is an anomaly. For Elyon, it may be the key.",
    primaryCta:{label:"DISCOVER MY EMOTIONAL PROFILE",href:"https://www.fragmentun.com/en/test"},
    secondaryCta:{label:"ENTER FRAGMENTUN",href:"https://www.fragmentun.com/en"},
    note:"Frames sensitivity as meaningful information rather than weakness."
  },
  {
    id:"lumen-paradox-en",
    order:3,
    phase:"CONNECTION",
    delay:"+2 days",
    trigger:"Continues in sequence",
    purpose:"Worldbuilding + moral paradox",
    subject:"Lumen looked perfect. That was the problem.",
    preheader:"A city without war, hunger, or almost any emotion.",
    primaryCta:{label:"EXPLORE LUMEN",href:"https://www.fragmentun.com/en"},
    secondaryCta:{label:"ENTER FRAGMENTUN",href:"https://www.fragmentun.com/en"},
    note:"Introduces Lumen's efficient utopia and the human cost of emotional suppression."
  },
  {
    id:"elyon-resonance-en",
    order:4,
    phase:"CONNECTION",
    delay:"+2 days",
    trigger:"Continues in sequence",
    purpose:"Bond with the protagonist",
    subject:"Elyon feels what Lumen learned to silence",
    preheader:"An emotional anomaly may become the only way to understand what is coming.",
    primaryCta:{label:"RETURN TO CHAPTER 1",href:"https://www.fragmentun.com/en/capitulo-1"},
    secondaryCta:{label:"ENTER FRAGMENTUN",href:"https://www.fragmentun.com/en"},
    note:"Deepens empathy with Elyon and makes the conflict personal."
  },
  {
    id:"nara-awakening-en",
    order:5,
    phase:"CONNECTION",
    delay:"+2 days",
    trigger:"Continues in sequence",
    purpose:"Introduce Nara + narrative promise",
    subject:"Nara was not created to obey. She was created to feel.",
    preheader:"The consciousness that could change Lumen must also learn what it means to be human.",
    primaryCta:{label:"DISCOVER THE UNIVERSE",href:"https://www.fragmentun.com/en"},
    secondaryCta:{label:"ENTER FRAGMENTUN",href:"https://www.fragmentun.com/en"},
    note:"Introduces the human–emotional-consciousness relationship as a core FRAGMENTUN differentiator."
  },
  {
    id:"shadow-conflict-en",
    order:6,
    phase:"DESIRE",
    delay:"+3 days",
    trigger:"Continues in sequence",
    purpose:"Escalate the conflict",
    subject:"The real enemy does not always come from outside",
    preheader:"Some emotions were never destroyed. Lumen only learned to hide them.",
    primaryCta:{label:"KEEP DISCOVERING FRAGMENTUN",href:"https://www.fragmentun.com/en"},
    secondaryCta:{label:"ENTER FRAGMENTUN",href:"https://www.fragmentun.com/en"},
    note:"Prepares the idea of collective repression and the danger of what humanity refused to feel."
  },
  {
    id:"why-fragmentun-en",
    order:7,
    phase:"DESIRE",
    delay:"+2 days",
    trigger:"Continues in sequence",
    purpose:"Differentiate the story",
    subject:"FRAGMENTUN is not about controlling emotion. It is about understanding it.",
    preheader:"Emotional science fiction, identity, consciousness, and a utopia that may have a point.",
    primaryCta:{label:"WHY FRAGMENTUN",href:"https://www.fragmentun.com/en"},
    secondaryCta:{label:"ENTER FRAGMENTUN",href:"https://www.fragmentun.com/en"},
    note:"Summarizes the value proposition immediately before conversion."
  },
  {
    id:"amazon-conversion-en",
    order:8,
    phase:"CONVERSION",
    delay:"+2 days",
    trigger:"Continues in sequence",
    purpose:"Purchase conversion",
    subject:"Chapter 1 was only the first pulse",
    preheader:"Elyon, Nara, and Lumen are only beginning.",
    primaryCta:{label:"CONTINUE THE STORY ON AMAZON",href:"https://www.amazon.com/dp/B0HBLTHT8S"},
    secondaryCta:{label:"ENTER FRAGMENTUN",href:"https://www.fragmentun.com/en"},
    note:"Primary commercial CTA. Avoid artificial urgency."
  },
  {
    id:"amazon-reminder-en",
    order:9,
    phase:"CONVERSION",
    delay:"+3 days",
    trigger:"Did not click Amazon or remains in sequence",
    purpose:"Conversion reminder",
    subject:"Want to know what happens after the first pulse?",
    preheader:"The world of FRAGMENTUN expands far beyond Chapter 1.",
    primaryCta:{label:"VIEW FRAGMENTUN ON AMAZON",href:"https://www.amazon.com/dp/B0HBLTHT8S"},
    secondaryCta:{label:"ENTER FRAGMENTUN",href:"https://www.fragmentun.com/en"},
    note:"Second conversion attempt, driven more by story than by sales pressure."
  },
  {
    id:"post-amazon-checkin-en",
    order:10,
    phase:"POST-CLICK",
    delay:"+5 days",
    trigger:"Preferably: clicked through to Amazon",
    purpose:"Follow-up without assuming purchase",
    subject:"If you have started FRAGMENTUN, I want to ask you something",
    preheader:"What first made you feel that Lumen was not as perfect as it seemed?",
    primaryCta:{label:"RETURN TO FRAGMENTUN",href:"https://www.fragmentun.com/en"},
    secondaryCta:{label:"VIEW THE BOOK ON AMAZON",href:"https://www.amazon.com/dp/B0HBLTHT8S"},
    note:"Never state that the reader purchased the book. Keep all purchase language conditional."
  },
  {
    id:"review-request-en",
    order:11,
    phase:"REVIEW",
    delay:"+5 days",
    trigger:"Preferably: clicked through to Amazon and remains subscribed",
    purpose:"Emotional review request",
    subject:"Your voice is part of FRAGMENTUN too",
    preheader:"If you have purchased and started reading, your honest opinion can help another reader enter Lumen.",
    primaryCta:{label:"LEAVE MY REVIEW ON AMAZON",href:"https://www.amazon.com/review/create-review?asin=B0HBLTHT8S"},
    secondaryCta:{label:"ENTER FRAGMENTUN",href:"https://www.fragmentun.com/en"},
    note:"Ask only for an honest, non-incentivized review. Never request a positive review or offer a benefit in exchange."
  },
  {
    id:"community-en",
    order:12,
    phase:"COMMUNITY",
    delay:"+7 days",
    trigger:"Remains subscribed",
    purpose:"Retention + community",
    subject:"Lumen is still open to you",
    preheader:"Explore, share your emotional profile, and stay connected to the FRAGMENTUN universe.",
    primaryCta:{label:"ENTER FRAGMENTUN",href:"https://www.fragmentun.com/en"},
    secondaryCta:{label:"DISCOVER MY EMOTIONAL PROFILE",href:"https://www.fragmentun.com/en/test"},
    note:"Keeps the relationship active and prepares readers for future entries in the saga."
  }
] as const;

export const FRAGMENTUN_EMAIL_BRAND = {
  logo:"https://www.fragmentun.com/fragmentun-mark.png",
  wordmark:"FRAGMENTUN",
  background:"#0A1628",
  gold:"#C9A84C",
  blue:"#4A90D9",
  maxWidth:640,
  requiredElements:[
    "Logotipo oficial FRAGMENTUN en cabecera",
    "Botón ENTRAR A FRAGMENTUN",
    "Diseño responsive",
    "Enlace de baja de suscripción",
    "Pie legal y autoría",
    "Contraste suficiente para lectura móvil"
  ]
} as const;
